#include <stdio.h>

void generate_svg_gauge(float progress) {
    // This C code "draws" a professional progress bar using SVG math
    FILE *f = fopen("analytics_gauge.html", "w");
    
    float width = progress * 4; // Map 0-100% to a 400px bar

    fprintf(f, "<div style='margin: 20px 0; font-family: sans-serif;'>\n");
    fprintf(f, "  <h4>Degree Completion Progress</h4>\n");
    fprintf(f, "  <svg width='400' height='30' style='background: #eee; border-radius: 15px;'>\n");
    fprintf(f, "    <rect width='%.1f' height='30' fill='#00529b' rx='15' />\n", width);
    fprintf(f, "    <text x='180' y='20' fill='white' font-weight='bold'>%.1f%%</text>\n", progress);
    fprintf(f, "  </svg>\n");
    fprintf(f, "  <p style='font-size: 0.8em; color: #666;'>Generated by C-Engine Analytics v1.0</p>\n");
    fprintf(f, "</div>\n");

    fclose(f);
    printf("Pro-level Analytics Gauge generated!\n");
}

int main() {
    // Real-world scenario: This would be calculated from your university_system data
    float my_current_progress = 72.5; 
    generate_svg_gauge(my_current_progress);
    return 0;
}